#!/usr/bin/env bash
# sync-pin-evidence.sh — emit the sync PR body's "pin evidence" section: for every
# MOVED gitlink, the STAGED GITLINK (the pinned commit this PR records) beside the
# owning repo's remote default-branch HEAD, plus the truthful statement of whether
# policy B can fail on THIS diff.
#
# Why this is its own script: the sync PR's body is generated by `.github/workflows/
# sync.yml` and must carry real, verifiable evidence that each moved pin is a merged
# default-branch HEAD (or charly's own gitlink, for `distro-*`). Extracting it here
# makes the logic TESTABLE in-tree (`--self-test`, run by the pre-commit gate), not a
# string nobody can exercise.
#
# The STAGED GITLINK — never the submodule's working-tree HEAD — is the pinned commit
# the umbrella records (`git ls-tree HEAD -- <path>`); a submodule that is
# uninitialised or sitting on another commit must not turn a correct pin into a false
# `not-equal`.
#
# Modes:
#   (default) <root> <policy-b-log>   read MOVED (one path per line) from stdin; print
#                                     the evidence section (table + coverage framing).
#   --self-test                       exercise pin_row + coverage_note on fixtures.
set -euo pipefail

KIND_DISTRO="charly-pinned (policy B)"
KIND_DEFAULT="default-branch HEAD"

# pin_row <path> <staged_gitlink> <remote_head> — ONE evidence row. The single
# implementation the live path and the self-test both call.
pin_row() {
  local p="$1" staged="$2" remote="$3" kind eq
  case "$p" in
    distro-*) kind="$KIND_DISTRO" ;;
    *)        kind="$KIND_DEFAULT" ;;
  esac
  if [ -n "$staged" ] && [ "$staged" = "$remote" ]; then eq="EQUAL"; else eq="not-equal"; fi
  printf '  %-28s staged-gitlink=%.12s remote-HEAD=%.12s  [%s, %s]\n' \
    "$p" "$staged" "$remote" "$kind" "$eq"
}

# coverage_note <distro_moved_count> — policy B asserts only `distro-*` gitlinks, so it
# is this diff's coverage ONLY when at least one `distro-*` pin moved. ONE decision,
# shared by the live path and the self-test.
coverage_note() {
  if [ "${1:-0}" -gt 0 ]; then
    echo "POLICY_B_IS_COVERAGE"
  else
    echo "POLICY_B_NOT_COVERAGE"
  fi
}

if [ "${1:-}" = "--self-test" ]; then
  fail() { echo "FAIL: sync-pin-evidence self-test: $*" >&2; exit 1; }

  # pin_row: distro-* is charly-pinned; equality classified by the STAGED gitlink.
  pin_row "distro-arch" "aaaa1111bbbb" "cccc2222dddd" | grep -q 'charly-pinned (policy B), not-equal' \
    || fail "distro-* row not classified charly-pinned/not-equal"
  pin_row "distro-arch" "same9999" "same9999" | grep -q 'charly-pinned (policy B), EQUAL' \
    || fail "distro-* equal staged/remote not EQUAL"
  pin_row "plugin-vm" "same9999" "same9999" | grep -q 'default-branch HEAD, EQUAL' \
    || fail "non-distro equal staged/remote not EQUAL"
  pin_row "plugin-vm" "aaaa1111" "cccc2222" | grep -q 'default-branch HEAD, not-equal' \
    || fail "non-distro mismatch not not-equal"
  pin_row "plugin-vm" "" "cccc2222" | grep -q 'not-equal' \
    || fail "empty staged gitlink not not-equal"
  # A LONGER name in the default class must classify as default (not charly-pinned).
  pin_row "plugin-vm-extra" "x" "y" | grep -q 'default-branch HEAD' \
    || fail "plugin-vm-extra wrongly classified charly-pinned"

  # coverage_note: both directions.
  [ "$(coverage_note 0)" = "POLICY_B_NOT_COVERAGE" ] || fail "0 distro moved should NOT offer policy B"
  [ "$(coverage_note 2)" = "POLICY_B_IS_COVERAGE" ] || fail ">0 distro moved should offer policy B"

  echo "sync-pin-evidence: self-test OK (per-pin classification both ways; coverage both directions)"
  exit 0
fi

ROOT="${1:?usage: sync-pin-evidence.sh <root> <policy-b-log>}"
POLICY_B_LOG="${2:?usage: sync-pin-evidence.sh <root> <policy-b-log>}"
cd "$ROOT"

MOVED="$(cat)"
DISTRO_MOVED=0

echo "**Default-branch HEAD, per moved pin.** For each moved path: the STAGED"
echo "GITLINK this PR records (\`git ls-tree HEAD -- <path>\`) beside the owning repo's"
echo "remote default-branch HEAD (\`git ls-remote <url> HEAD\`). \`charly\` and every"
echo "non-\`distro-*\` repo must be EQUAL; a \`distro-*\` pin tracks charly's own gitlink"
echo "and is proven by policy B, so it is marked \`charly-pinned\` and not required"
echo "equal here:"
echo
echo '```'
while IFS= read -r p; do
  [ -n "$p" ] || continue
  staged=$(git ls-tree HEAD -- "$p" 2>/dev/null | awk '{print $3}')
  [ -n "$staged" ] || staged=$(git rev-parse ":$p" 2>/dev/null || echo '?')
  url=$(git config -f .gitmodules --get "submodule.$p.url" 2>/dev/null || echo '')
  remote=$(git ls-remote "$url" HEAD 2>/dev/null | awk '{print $1}' || echo '')
  case "$p" in distro-*) DISTRO_MOVED=$((DISTRO_MOVED + 1)) ;; esac
  pin_row "$p" "$staged" "$remote"
done <<< "$MOVED"
echo '```'
echo
if [ "$(coverage_note "$DISTRO_MOVED")" = "POLICY_B_IS_COVERAGE" ]; then
  echo "**Policy B — the assertion this diff CAN violate** (\`${DISTRO_MOVED}\`"
  echo "\`distro-*\` pin(s) moved). \`scripts/check-policy-b.sh\` reads charly's own"
  echo "gitlinks with \`git ls-tree\` (tree objects — present in a shallow clone;"
  echo "charly's NESTED submodules need not be initialised) and asserts every umbrella"
  echo "\`distro-*\` gitlink equals it, pasted verbatim from this run:"
  echo
  echo '```'
  cat "$POLICY_B_LOG"
  echo '```'
else
  echo "**Policy B is NOT offered as this diff's coverage:** it asserts the umbrella"
  echo "\`distro-*\` gitlinks equal charly's own, and **this diff moved zero \`distro-*\`"
  echo "pins**, so that gate cannot fail on this diff. The coverage for the pins that"
  echo "DID move is the per-pin \`git ls-remote\` default-branch evidence above (and, for"
  echo "\`charly\`, its own default-branch HEAD). For transparency the policy-B gate still"
  echo "ran and passed:"
  echo
  echo '```'
  cat "$POLICY_B_LOG"
  echo '```'
fi
