#!/usr/bin/env bash
# sync-pin-evidence.sh — emit the sync PR body's "pin evidence" section: for every
# MOVED gitlink, the STAGED GITLINK (the pinned commit this PR records) beside the
# owning repo's remote default-branch HEAD, plus the truthful statement of whether
# policy B can fail on THIS diff.
#
# Why this is its own script: the sync PR's body is generated by `.github/workflows/
# sync.yml` and must carry real, verifiable evidence that each moved pin is a merged
# default-branch HEAD (or charly's own gitlink, for `distro-*`). Extracting it here
# makes the logic TESTABLE in-tree (`--self-test`, run by the pre-commit gate), not a
# string nobody can exercise.
#
# The STAGED GITLINK — never the submodule's working-tree HEAD — is the pinned commit
# the umbrella records (`git ls-tree HEAD -- <path>`); a submodule that is
# uninitialised or sitting on another commit must not turn a correct pin into a false
# `not-equal`.
#
# Modes:
#   (default) <root> <policy-b-log>   read MOVED (one path per line) from stdin; print
#                                     the evidence section (table + coverage framing).
#   --self-test                       exercise pin_row + coverage_note on fixtures.
#
# SIZE BOUND (a GitHub platform limit, not a preference). A sync PR body is capped by
# GitHub at 65536 characters; a sync that moves hundreds of pins (measured: 393 after
# the org-wide ruleset cutover) overflows it and `gh pr create` fails with
# "Body is too long". The per-pin evidence table is the largest section, so it is
# emitted up to SYNC_EVIDENCE_MAX_BYTES (default 40000) and then truncated with an
# explicit elision notice naming shown/total. Two things keep A1 accounting complete
# despite the bound: the workflow's "Every changed path, named" list is itself bounded
# to SYNC_PATH_LIST_MAX and carries a `(first N of M …)` hint naming the TRUE total, and
# the workflow writes the RENDERED rows of this table (not just an unrendered log) plus
# the moved-path list into the `sync-evidence` run artifact the body links to — so every
# moved pin is named (in the body's count) and every elided row is retrievable (artifact).

SYNC_EVIDENCE_MAX_BYTES="${SYNC_EVIDENCE_MAX_BYTES:-40000}"
set -euo pipefail

KIND_DISTRO="charly-pinned (policy B)"
KIND_DEFAULT="default-branch HEAD"

# pin_row <path> <staged_gitlink> <remote_head> — ONE evidence row. The single
# implementation the live path and the self-test both call.
pin_row() {
  local p="$1" staged="$2" remote="$3" kind eq
  case "$p" in
    distro-*) kind="$KIND_DISTRO" ;;
    *)        kind="$KIND_DEFAULT" ;;
  esac
  if [ -n "$staged" ] && [ "$staged" = "$remote" ]; then eq="EQUAL"; else eq="not-equal"; fi
  printf '  %-28s staged-gitlink=%.12s remote-HEAD=%.12s  [%s, %s]\n' \
    "$p" "$staged" "$remote" "$kind" "$eq"
}

# coverage_note <distro_moved_count> — policy B asserts only `distro-*` gitlinks, so it
# is this diff's coverage ONLY when at least one `distro-*` pin moved. ONE decision,
# shared by the live path and the self-test.
coverage_note() {
  if [ "${1:-0}" -gt 0 ]; then
    echo "POLICY_B_IS_COVERAGE"
  else
    echo "POLICY_B_NOT_COVERAGE"
  fi
}

# bounded_rows <budget_bytes> <total_count> — read candidate rows (one per line, each
# already rendered) from stdin and print them until adding the next would exceed
# <budget_bytes>, always emitting AT LEAST the first row. When truncation occurs, print a
# final elision line naming shown/total. ONE implementation the live path and the
# self-test both call — this is the 65536-char body-cap guard.
bounded_rows() {
  local budget="$1" total="$2" bytes=0 rows=0 truncated=0 line bytes_line
  while IFS= read -r line; do
    bytes_line=$(( ${#line} + 1 ))
    if [ "$rows" -gt 0 ] && [ $((bytes + bytes_line)) -gt "$budget" ]; then
      truncated=1; break
    fi
    printf '%s\n' "$line"
    bytes=$((bytes + bytes_line)); rows=$((rows + 1))
  done
  if [ "$truncated" -eq 1 ]; then
    echo "  … $rows of $total rows shown; the remaining $((total - rows)) are in the 'sync-evidence' run artifact"
  fi
}

# staged_gitlink <root> <path> — the gitlink this PR RECORDS for <path>. It reads the
# INDEX (`:<path>`), because the body is generated AFTER `git add -A` and BEFORE the
# commit: HEAD still points at the previous snapshot, so `HEAD:<path>` would name the
# OLD pin. Falls back to HEAD only when the path is not staged (already committed).
# The submodule's WORKING-TREE HEAD is NEVER read: it can be uninitialised or on
# another commit and would turn a correct pin into a false not-equal.
staged_gitlink() {
  local root="$1" p="$2" sha
  # Scrub git's hook-exported repo vars so `-C "$root"` truly targets $root: when
  # this runs from a hook (the self-test), GIT_DIR/GIT_INDEX_FILE name the CALLING
  # repo and would override -C (measured: it corrupted the umbrella's config).
  unset GIT_DIR GIT_INDEX_FILE GIT_WORK_TREE GIT_COMMON_DIR GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES
  # `--verify --quiet` is the load-bearing fix (measured): bare `git rev-parse
  # ":$p"` ECHOES the literal `:<path>` token on failure and exits non-zero, so
  # `-n "$sha"` passed and the HEAD fallback below never ran for an unstaged path.
  # `--verify --quiet` prints nothing and exits 1; `|| true` keeps that non-zero
  # from aborting under `set -e` in any caller that inherits errexit.
  sha=$(git -C "$root" rev-parse --verify --quiet ":$p" || true)
  [ -n "$sha" ] || sha=$(git -C "$root" ls-tree HEAD -- "$p" 2>/dev/null | awk '{print $3}')
  printf '%s' "$sha"
}

if [ "${1:-}" = "--self-test" ]; then
  fail() { echo "FAIL: sync-pin-evidence self-test: $*" >&2; exit 1; }

  # pin_row: distro-* is charly-pinned; equality classified by the STAGED gitlink.
  pin_row "distro-arch" "aaaa1111bbbb" "cccc2222dddd" | grep -q 'charly-pinned (policy B), not-equal' \
    || fail "distro-* row not classified charly-pinned/not-equal"
  pin_row "distro-arch" "same9999" "same9999" | grep -q 'charly-pinned (policy B), EQUAL' \
    || fail "distro-* equal staged/remote not EQUAL"
  pin_row "plugin-vm" "same9999" "same9999" | grep -q 'default-branch HEAD, EQUAL' \
    || fail "non-distro equal staged/remote not EQUAL"
  pin_row "plugin-vm" "aaaa1111" "cccc2222" | grep -q 'default-branch HEAD, not-equal' \
    || fail "non-distro mismatch not not-equal"
  pin_row "plugin-vm" "" "cccc2222" | grep -q 'not-equal' \
    || fail "empty staged gitlink not not-equal"
  # A LONGER name in the default class must classify as default (not charly-pinned).
  pin_row "plugin-vm-extra" "x" "y" | grep -q 'default-branch HEAD' \
    || fail "plugin-vm-extra wrongly classified charly-pinned"

  # coverage_note: both directions.
  [ "$(coverage_note 0)" = "POLICY_B_NOT_COVERAGE" ] || fail "0 distro moved should NOT offer policy B"
  [ "$(coverage_note 2)" = "POLICY_B_IS_COVERAGE" ] || fail ">0 distro moved should offer policy B"

  # bounded_rows: the 65536-char body-cap guard. A generous budget emits every row and
  # NO elision notice; a tiny budget emits at least ONE row plus an elision naming
  # shown/total (so a huge sync can never overflow the body nor emit an empty fence).
  rows_all=$(printf 'r1\nr2\nr3\n' | bounded_rows 1000 3)
  [ "$(printf '%s\n' "$rows_all" | grep -c .)" = "3" ] || fail "generous budget must emit all 3 rows"
  printf '%s\n' "$rows_all" | grep -q 'elided\|rows shown' && fail "generous budget must not emit an elision notice"
  rows_cap=$(printf 'aaaaaaa\nbbbbbbb\nccccccc\nddddddd\n' | bounded_rows 10 4)
  echo "$rows_cap" | grep -q '^aaaaaaa$' || fail "bounded_rows must emit at least the first row at a tiny budget"
  echo "$rows_cap" | grep -q 'rows shown' || fail "bounded_rows must emit an elision notice when truncating"
  echo "$rows_cap" | grep -q '3 rows shown\|1 of 4 rows shown\|1 of 4' || fail "elision notice must name shown/total"

  # staged_gitlink: a REAL fixture repo where the STAGED pin differs from both the
  # HEAD pin and any submodule working-tree state — so reading the working tree (or
  # HEAD before the staged bump) FAILS this arm.
  #
  # CRITICAL: git exports GIT_DIR / GIT_INDEX_FILE / GIT_WORK_TREE to hook
  # processes, and `-C "$tmp"` does NOT override them — so a bare `git -C "$tmp"
  # …` here would write into the CALLING repo (measured: it set core.bare=true,
  # user.*, and a stray `sub` gitlink in the umbrella). Run the fixture ops in a
  # subshell with those variables scrubbed, so the fixture is fully isolated.
  tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
  fixture() (
    unset GIT_DIR GIT_INDEX_FILE GIT_WORK_TREE GIT_COMMON_DIR GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES
    cd "$tmp"
    git init -q
    git config user.email t@t; git config user.name t
    git update-index --add --cacheinfo 160000,1111111111111111111111111111111111111111,sub
    git commit -qm one
    # stage a NEW gitlink, leaving HEAD at the old one:
    git update-index --add --cacheinfo 160000,2222222222222222222222222222222222222222,sub
  )
  fixture >/dev/null
  got=$(staged_gitlink "$tmp" sub)
  [ "$got" = "2222222222222222222222222222222222222222" ] \
    || fail "staged_gitlink read '$got', want the STAGED index pin (2222…), not HEAD/working-tree"

  # staged_gitlink: a path ABSENT from the index must fall back to HEAD — and must
  # NOT abort the script under `set -e` (a bare `sha=$(git rev-parse …)` whose
  # substitution fails would exit here before the fallback could run).
  got=$(staged_gitlink "$tmp" absent-path) || fail "staged_gitlink aborted on an unstaged path (the set -e / fallback defect)"
  [ -z "$got" ] \
    || fail "staged_gitlink on an absent path read '$got', want empty (no index entry, no HEAD entry)"
  # A path that IS in HEAD but NOT in the index: stage new, commit, then delete the
  # index entry while HEAD keeps the old pin — the fallback must return HEAD's pin.
  fixture2() (
    unset GIT_DIR GIT_INDEX_FILE GIT_WORK_TREE GIT_COMMON_DIR GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES
    cd "$tmp"
    git update-index --add --cacheinfo 160000,3333333333333333333333333333333333333333,sub2
    git commit -qm two
    git update-index --force-remove sub2
  )
  fixture2 >/dev/null
  got=$(staged_gitlink "$tmp" sub2)
  [ "$got" = "3333333333333333333333333333333333333333" ] \
    || fail "staged_gitlink fallback read '$got', want HEAD's 3333… for an unstaged path"

  echo "sync-pin-evidence: self-test OK (per-pin classification both ways; coverage both directions; bounded_rows emits all under budget and >=1 + elision notice over budget; staged-gitlink reads the index + falls back to HEAD)"
  exit 0
fi

ROOT="${1:?usage: sync-pin-evidence.sh <root> <policy-b-log>}"
POLICY_B_LOG="${2:?usage: sync-pin-evidence.sh <root> <policy-b-log>}"
cd "$ROOT"

MOVED="$(cat)"
MOVED_COUNT=$(printf '%s\n' "$MOVED" | grep -c . || true); MOVED_COUNT=${MOVED_COUNT:-0}
# Count distro-* over ALL moved paths (path prefix only — no network), so policy-B
# coverage is decided from the full diff, never from the truncated emission window.
DISTRO_MOVED=$(printf '%s\n' "$MOVED" | grep -c '^distro-' || true); DISTRO_MOVED=${DISTRO_MOVED:-0}

echo "**Default-branch HEAD, per moved pin.** For each moved path: the STAGED"
echo "GITLINK this PR records (\`git rev-parse --verify --quiet :<path>\` from the index, \`git ls-tree HEAD\` fallback) beside the owning"
echo "remote default-branch HEAD (\`git ls-remote <url> HEAD\`). \`charly\` and every"
echo "non-\`distro-*\` repo must be EQUAL; a \`distro-*\` pin tracks charly's own gitlink"
echo "and is proven by policy B, so it is marked \`charly-pinned\` and not required"
echo "equal here:"
echo
echo '```'
# Render every row to a temp file, THEN bound — never pipe the producer into the bounder.
# This environment ignores SIGPIPE, so an early-exiting bounder would leave the producer
# writing to a closed pipe; under `set -o pipefail` those failed writes would abort the
# script. A file sidesteps that entirely (only a few hundred rows).
ROWS_FILE="$(mktemp)"; trap 'rm -f "$ROWS_FILE"' EXIT
while IFS= read -r p; do
  [ -n "$p" ] || continue
  pin_row "$p" "$(staged_gitlink "$ROOT" "$p")" \
    "$(git ls-remote "$(git config -f .gitmodules --get "submodule.$p.url" 2>/dev/null || echo '')" HEAD 2>/dev/null | awk '{print $1}' || echo '')" \
    >> "$ROWS_FILE"
done <<< "$MOVED"
bounded_rows "$SYNC_EVIDENCE_MAX_BYTES" "$MOVED_COUNT" < "$ROWS_FILE"
echo '```'
# When the caller asks, persist the FULL rendered table so the elision notice's promise
# ("the remaining N are in the sync-evidence run artifact") is TRUE — the artifact gets
# the rendered rows, not just an unrendered producer log.
if [ -n "${SYNC_EVIDENCE_OUT:-}" ]; then
  {
    echo
    echo "== per-pin evidence table (full, all ${MOVED_COUNT} rows) =="
    cat "$ROWS_FILE"
  } >> "$SYNC_EVIDENCE_OUT"
fi
echo
if [ "$(coverage_note "$DISTRO_MOVED")" = "POLICY_B_IS_COVERAGE" ]; then
  echo "**Policy B — the assertion this diff CAN violate** (\`${DISTRO_MOVED}\`"
  echo "\`distro-*\` pin(s) moved). \`charly task policy-b\` reads charly's own"
  echo "gitlinks with \`git ls-tree\` (tree objects — present in a shallow clone;"
  echo "charly's NESTED submodules need not be initialised) and asserts every umbrella"
  echo "\`distro-*\` gitlink equals it, pasted verbatim from this run:"
  echo
  echo '```'
  cat "$POLICY_B_LOG"
  echo '```'
else
  echo "**Policy B is NOT offered as this diff's coverage:** it asserts the umbrella"
  echo "\`distro-*\` gitlinks equal charly's own, and **this diff moved zero \`distro-*\`"
  echo "pins**, so that gate cannot fail on this diff. The coverage for the pins that"
  echo "DID move is the per-pin \`git ls-remote\` default-branch evidence above (and, for"
  echo "\`charly\`, its own default-branch HEAD). For transparency the policy-B gate still"
  echo "ran and passed:"
  echo
  echo '```'
  cat "$POLICY_B_LOG"
  echo '```'
fi
